### PR TITLE
Patch PlayerControl.CheckColor

### PR DESCRIPTION
**Pull request by amsryq**
Apparently PlayerControl.CheckColor method was the one that sending normal RPC.

### CODE REVIEW

**Comment by DaemonBeast** [comment]
Looks good. I'll merge it after testing it (hopefully sometime soon, though I'm keeping no promises 😂).

**Comment by amsryq** [comment]
merge when

**Comment by DaemonBeast** [comment]
@amsyarasyiq never 😎

**Comment by amsryq** [comment]
😡

**Pull request closed without merging**
