### PR TITLE
Use the official color because why not

### PR DESCRIPTION
**Pull request by amsryq**
The most useful pull request you've ever seen

### CODE REVIEW

**Comment by DaemonBeast** [comment]
Have both colours because why not 🤯

I'll consider whether or not both should be in the mod. They both seem to contrast enough. I'll probably call them light maroon and dark maroon.

**Comment by amsryq** [comment]
Might continue again once Innersloth reveal all their color at SGF

**Comment by amsryq** [comment]
For some reason they reworked the Maroon color

What do you think? I renamed the current one to Light Maroon (LTMRN) and the official one to Maroon (MARN)

**Review by DaemonBeast — CHANGES_REQUESTED** [review]
- You added another coral, despite it already being in the list
- I'd prefer if the `255` green value in the mint colour remained as `255` and not `Byte.MaxValue`, as it looks more consistent.

**Comment by DaemonBeast** [comment]
Also, they didn't rework the maroon. It was never announced and it was just chance that it was added to the mod before it was revealed XD.

**Edit:** I guess they did rework it.

**Review by DaemonBeast — APPROVED** [review]

**Pull request merged**
